/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClipboardEntry {
  id: number
  type: number
  path: string
  content: string
  timestamp: number
  uuid: string
}
export interface ClipboardList {
  entries: Array<ClipboardEntry>
}
export declare class JsClipboardHelper {
  static new(logLevel?: number, sqlLevel?: number): Promise<JsClipboardHelper>
  refreshClipboard(): Promise<void>
  getClipboardEntries(num: number, typeInt?: number | undefined): Promise<ClipboardList>
  getClipboardEntriesByTypeList(num: number, typeList?: number[] | undefined): Promise<ClipboardList>
  searchClipboardEntries(query: string, num: number, typeInt?: number | undefined): Promise<ClipboardList>
  searchClipboardEntriesByTypeList(query: string, num: number, typeList?: number[] | undefined): Promise<ClipboardList>
  updateConfig(config: string): Promise<void>
  deleteEntryById(id: number): Promise<void>
}
