/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClipboardEntry {
  id: number
  type: number
  path: string
  content: string
  timestamp: number
  uuid: string
}
export interface ClipboardList {
  entries: Array<ClipboardEntry>
}
export declare class JsClipboardHelper {
  static new(dbPath: string): Promise<JsClipboardHelper>
  getAllClipboardEntries(): Promise<ClipboardList>
  getNumClipboardEntries(num: number): Promise<ClipboardList>
  nowGetContent(): Promise<void>
  search(query: string, n: number, contentType: number): Promise<ClipboardList>
}
