name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            targets: ['x86_64-apple-darwin', 'aarch64-apple-darwin']
          - platform: ubuntu-latest
            targets: ['x86_64-unknown-linux-gnu']
          - platform: windows-latest
            targets: ['x86_64-pc-windows-msvc']

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./client/supercv-vue

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        targets: ${{ join(matrix.targets, ' ') }}

    - name: Install Linux dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install dependencies
      run: npm install

    - name: Build Tauri App
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: ./client/supercv-vue
        tagName: v__VERSION__
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false

    - name: Build for specific targets
      if: matrix.platform == 'macos-latest'
      run: |
        for target in ${{ join(matrix.targets, ' ') }}; do
          npm run tauri build -- --target $target
        done